In [8]:
import numpy as np
print(np.__version__)

2.0.0


In [6]:
import sys
list = [1,23,4,5]
print(list)
print(sys.getsizeof(list))

[1, 23, 4, 5]
88


In [11]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.size)

[1 2 3 4 5]
5


In [17]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [16]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Built In Functions in NumPy

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [21]:
#zeros and ones
np.zeros(3)

array([0., 0., 0.])

In [26]:
arr=np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
#eye
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
#Random
#rand
np.random.rand(2)

array([0.1592407 , 0.03595292])

In [29]:
arr = np.random.rand(5,5)
print(arr)

[[0.18116914 0.55420237 0.54704516 0.39514136 0.58696646]
 [0.81587756 0.47438178 0.86337578 0.99407694 0.45714385]
 [0.63018101 0.07494994 0.06296003 0.73466284 0.98294026]
 [0.06794985 0.04674956 0.64020583 0.12260486 0.6830948 ]
 [0.75518927 0.35832907 0.48655029 0.25182386 0.01457252]]


In [33]:
#randn(generates random matrix numbers with negative integers also
arr=np.random.randn(2,2)
print(arr)

[[-1.57607676  0.06542822]
 [-0.90747362 -0.56452683]]


In [34]:
#randint
np.random.randint(1,100)

49

In [35]:
np.random.randint(1,100,10)

array([90, 37, 74, 18, 53, 31, 68, 13, 52, 43], dtype=int32)

In [36]:
arr = np.random.randint(1,100,10)
print(arr)

[89 87 91  3 54 18 39 37 64 89]


Array Attributes and Methods

In [42]:
arr = np.random.randint(5,100,5)
print(arr)

[98 67 10 33 72]


In [44]:
print(arr.max())
print(arr.min())
print(arr.mean())


98
10
56.0


Numpy Indexing and Slicing


In [45]:
#Bracket indexing and slicing
#simple way to pick one or some elements of an array

arr = np.arange(0,10)
print(arr)
print(arr[5])
arr[0:5]

[0 1 2 3 4 5 6 7 8 9]
5


array([0, 1, 2, 3, 4])

In [46]:
#Broadcasting
#Setting the value with index range
arr[0:5] = 100
print(arr)


[100 100 100 100 100   5   6   7   8   9]


In [48]:
arr = np.arange(0,10)
print(arr)
slice_of_arr = arr[0:5]
slice_of_arr[:]=99
slice_of_arr

[0 1 2 3 4 5 6 7 8 9]


array([99, 99, 99, 99, 99])

Indexing a 2D Array


In [49]:
arr_2nd = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2nd)
print(arr_2nd[1])
print(arr_2nd[1][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
5


In [ ]:
#2D array slicing
#shape (2,2) from top right corner

